name = "kirala_l4u"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.36"
qdate = "~> 0.7"
jsone = "~> 1.8"
bbmustache = "~> 1.12"
gleam_bbmustache = "~> 2.2"

[dev-dependencies]
gleeunit = "~> 1.0"
